version: '3.1'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  #server:
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
  #  container_name: server
  #  restart: always
  #  ports:
  #    - '8080:8080'
  #  environment:
  #    - IS_PUSH_METRIC=false
  #    - PUSH_HOST=http://prometheus_push:9091

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    restart: always
  #  prometheus_push:
  #    image: prom/pushgateway:latest
  #    volumes:
  #      - ./prometheus_push/:/etc/prometheus/
  #    command:
  #      - '--web.listen-address=0.0.0.0:9091'
  #      - '--persistence.file=true'
  #    ports:
  #      - '9091:9091'
  #    restart: always
volumes:
  prometheus_data:
  grafana-storage:
