global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ '0.0.0.0:9090' ]
  - job_name: server
    metrics_path: /metrics
    static_configs:
      - targets:
          - server:8080
          - host.docker.internal:9000
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['0.0.0.0:9091']
